export const SET_POST = 'SET_POST';
export const SET_EDITED_POST = 'SET_EDITED_POST';
export const TOGGLE_CREATE_MODE = 'TOGGLE_CREATE_MODE';
export const SET_SNACKBAR_CLOSE = 'SET_SNACKBAR_CLOSE';
export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE';
export const TOGGLE_SUCCESS_SNACKBAR = 'TOGGLE_SUCCESS_SNACKBAR';
export const TOGGLE_ERROR_SNACKBAR = 'TOGGLE_ERROR_SNACKBAR';
export const SET_VALIDATION_ERROR = 'SET_VALIDATION_ERROR';




